#!/bin/bash

# First obtain a location code from: https://weather.codes/united-states-of-america/florida/

# Insert your location. For example USFL0179 is the location code for Green Cove Springs, FL
location="USFL0179"
tmpfile=/tmp/$location.out

# Obtain sunrise and sunset raw data from weather.com
wget -q "https://weather.com/weather/today/l/$location" -O "$tmpfile"

SUNR=$(grep SunriseSunset "$tmpfile" | grep -oE '((1[0-2]|0?[1-9]):([0-5][0-9]) ?([AaPp][Mm]))' | head -1)
SUNS=$(grep SunriseSunset "$tmpfile" | grep -oE '((1[0-2]|0?[1-9]):([0-5][0-9]) ?([AaPp][Mm]))' | tail -1)


sunrise=$(date --date="$SUNR" +%r)
sunset=$(date --date="$SUNS" +%r)

# Use $sunrise and $sunset variables to fit your needs. Example:
echo "$sunrise" > /usr/local/bin/sunrise
echo "$sunset" > /usr/local/bin/sunset
